stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install ruff
  script:
    - ruff check .

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest
